version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
    - 0.80.1
  - dependency-name: docker-api
    versions:
    - 2.0.0
